spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/altiv_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysqldb/authDB?createDatabaseIfNotExist=true #docker container
    username: root
    #password: root1234
    password: root #mysql docker container password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9292/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin       
        
#spring:
#  profiles:
#    active:
#    -         

