altiv:
  db:
    connection: "{ConnectionString:'http://__',userName:'foo',password:'pass'}"
    host: 127.0.0.0
    port: 3306
  applicationName: Altiv
  greeting: Welcome to ${altiv.applicationName} community
  exchangeOptions: barter,money,bank-time
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/altiv_db?createDatabaseIfNotExist=true
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
