server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EduardoGonzalezHerrera/exchangePlatform.git     	
          search-paths:
          - 'backEnd/'
          - 'altiv-config/*service'
          
      
