altiv:
  db:
    connection: "{ConnectionString:'http://__',userName:'foo',password:'pass'}"
    host: 127.0.0.0
    port: 3306
  applicationName: AltivTest
  greeting: Welcome to ${altiv.applicationName} community
  exchangeOptions: barter,money,bank-time  
     

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

         

