server:
  port: 9292
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true #no docker container
    url: jdbc:mysql://mysqldb/authDB?createDatabaseIfNotExist=true #docker container
    username: root
    #password: root1234 #mysql localhost password
    password: root #mysql docker container password
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:  
  